name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels:
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue. Please fill out the details below.
  - type: input
    id: package_version
    attributes:
      label: Package version
      description: Version from package.json or npm
      placeholder: "2.0.1"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser + OS (and framework if relevant)
      placeholder: "Chrome 121 on Windows 11, Next.js 14"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Clear steps so we can reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "What you expected to happen"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "What actually happened"
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Logs, screenshots, or other details
