name: Feature request
description: Suggest an idea or improvement
title: "[Feature]: "
labels:
  - "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please share the details below.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem are you trying to solve?
      placeholder: "As a user, I want..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions or workarounds?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, references, mockups, etc.
